- conf/layer.conf
Update layer compatibility to styhead and also making the dependency on oe-core , meata-qcom-hwe explicit.
> Move to styhead and update layer depends

- recipes-products/images/qcom-minimal-image.bb
The debug-tweaks IMAGE_FEATURE has been removed so replace it with corresponding suggested features.
> qcom-minimal-image: replace debug-tweaks IMAGE_FEATURE

- conf/distro/include/qcom-base.inc
Enable 'efi' distro feature to gain EFI support in, among other things, systemd. This enable EFI support in bootctl and systemd-boot.
> qcom distro: enable 'efi' DISTRO_FEATURE

- conf/layer.conf
Update layer.conf to reflect compatibility with walnascar release and drop deprecated qcom-hwe dependencies.
> Update layer.conf 

- recipes-kernel/linux/linux-yocto/kernel_cmdline_extra.cfg
- recipes-kernel/linux/linux-yocto_6.6.bbappend
Remove linux-yocto_6.6 append and related cfgs, as it was removed from OE-Core
> Remove linux-yocto 6.6 bbappend

- conf/distro/include/qcom-base.inc
This is heavily based on the KAS config from meta-qcom-hwe.git
The meta-qcom layer is locked to a commit that still has initramfs-qcom-image, the build won't start otherwise. This also includes inherits that should *not* be in the CI config, but in the DISTRO.conf.
> meta-qcom-distro: select package_ipk

- recipes-products/images/qcom-minimal-image.bb
Making entire rootfs as read-only breaks Ostree usage. It requires the OS read-only content is limited only to /usr. Dropping read-only-rootfs from IMAGE_FEATURES for now validate OStree.
> Drop read-only-rootfs from IMAGE_FEATURES

- conf/distro/include/qcom-base.inc
Using ??= will use the `DISTRO_VERSION ?= "nodistro.0"` from `default-distrovars.inc`, which is not what we want. Explicitly set it to `2.0` to mark it as the preparation for QLI2.x that it is.
> qcom-base.inc: explicitly set DISTRO_VERSION

- conf/distro/include/qcom-base.inc
To get connectivity working, firmware package groups in meta-qcom should include Bluetooth and Wi-Fi firmware, which are controlled by the bluetooth and wifi DISTRO_FEATURES
> Add bluetooth, wifi to DISTRO_FEATURES

- conf/distro/include/qcom-base.inc
Enable predictable network interface names by default in order to allow a stable interface naming during boot.
Without pni-names the interfaces assigned are done at random order, which is an issue on devices with multiple network interfaces such as qcs9100-ride-sx.
> qcom-base: add pni-names to DISTRO_FEATURES

- conf/distro/include/qcom-base.inc
No functional change, just reordering alphabetically.
> qcom-base: order DISTRO_FEATURES alphabetically

- classes/image-adbd.bbclass
We enforce copyright and license declaration for bbclass files as part of our repolinter logic.
> image-adbd.bbclass: add missing copyright and license declaration

- recipes-products/images/qcom-console-image.bb
- recipes-products/images/qcom-minimal-image.bb
- recipes-products/packagegroups/packagegroup-qcom-utilities.bb
Define a package group with common utilities required for QCOM images. 
Previously, these utilities were added to packagegroup-qcom via a bbappend. However, some of the utilities, like libinput, force the PACKAGE_ARCH to be updated, which can cause confusion for users.
Dropping the append and adding these utilities in a new packagegroup would be a much cleaner implementation.
> Define packagegroup-qcom-utilities

- recipes-core/systemd/systemd_%.bbappend
We do not want MAC address based naming, for example the wifi on RB1 gets a new MAC address every boot *and* doesn't support any of the naming features. This leads to a new, unpredictable interface name on every boot.
Having 'wlan0' and 'eth0' for such interfaces is better than 'wn<random mac>', but we do want supported interfaces (e.g. PCIe and USB attached ones) to get renamed, so disabling pni-names completely is unwanted.
> systemd bbappend: disable 'mac' policy for pni-names

- conf/distro/include/qcom-base.inc
Locking GCC to an unavailable errors does nothing but generate warnings:
WARNING: versions of gcc-runtime available: 15.1.0
WARNING: preferred version 14.2% of gcc not available (for item cpp)
WARNING: versions of gcc available: 15.1.0
Drop the version lock completely for the master branch.
> qcom distro: GCC 14.x was removed from OE-core, remove version lock

- conf/distro/qcom.conf
This uses the same base as the qcom-wayland distro, but enables X11 instead. This is needed for showing things like XFCE that don't have a native wayland port yet.
> qcom-x11: add X11 based distro config

- conf/layer.conf
Add explicit layer dependency on openembedded-layer to satisfy dependency required for adb support.
While we could change the image_adbd class to only depend on android-tools-adbd when openembedded-layer is available, it is better to assume it will always be for better user experience.
Since we also expect to extend our distro images to also include additional recipes from the same layer, better to just have it as an explicit dependency.
> layer: add dependency on openembedded-layer

- recipes-products/images/qcom-minimal-image.bb
- System user is really legacy and shouldn't be used or required
- Make sure there is a default password for root and drop allow-empty-password and empty-root-password from image features
> Remove system user and add password for root

- conf/layer.conf
- recipes-products/images/qcom-console-image.bb
- recipes-products/packagegroups/packagegroup-qcom-utilities.bb
- Add packagegroup-qcom-utilities-network-utils covering additional network related tooling and utilities
- Add meta-networking and meta-python (dependency of meta-networking) as meta-qcom-distro layer dependency
> Extend images to include network utilities

- conf/distro/include/qcom-base.inc
* Remove settings that are not required or used
* Include security_flags and yocto-space-optimize from the oe-core
> qcom-base distro cleanups

- conf/distro/qcom-distro.conf
Rename default distro name from qcom to qcom-distro to avoid override confusion from the soc family override set in meta-qcom.
As 'qcom-distro' is a clean override, drop local 'qcom-wayland' replacement for the override, since there are no users for it.
> distro: rename distro name to qcom-distro

- conf/layer.conf
- recipes-multimedia/libcamera/libcamera_%.bbappend
- recipes-products/images/qcom-xfce-demo-image.bb
- recipes-products/packagegroups/packagegroup-qcom-distro-xfce.bb
- recipes-products/packagegroups/packagegroup-qcom-utilities.bb
This adds the recipe used for the EW25 demo, as part of a dynamic layer setup. This should hide the recipe until the user has included meta-xfce and all its dependencies.
> RFC: Add meta-xfce as a dynamic layer

- conf/layer.conf
There are no breaking changes in the qcom-distro layer, so simply mark it as compatible with the next OE branch, whinlatter.
> layer.conf: mark qcom-distro as compatible with whinlatter release

- recipes-crypto/libkcapi/libkcapi_%.bbappend
- recipes-products/images/qcom-multimedia-image.bb
- recipes-products/packagegroups/packagegroup-qcom-test-pkgs.bb
- recipes-products/packagegroups/packagegroup-qcom-utilities.bb
1. Add below utilities to packagegroup-qcom-test-pkgs.bb which will be used to test QCOM image and add the packagegroup packagegroup-qcom-test-pkgs to qcom-multimedia-image
- igt-gpu-tools ->will be used to test display
- iperf3 -> will be used for USB/PCIe
- libkcapi -> enable applications to utilize kernel-level cryptographic functionality
- lmbench -> It is a tool used for performance analysis
- tinyalsa -> tinyplay, tinycap will be used to test Audio playback and recording via USB headset
2. Enable testapp packageconfig for libkcapi to enable kcapi test program in libkcapi bbappend
> qcom-multimedia-image: Add packagegroup-qcom-test-pkgs to test QCOM image

- recipes-products/packagegroups/packagegroup-qcom-utilities.bb
- hostapd is added to support wireless access point functionality.
- trace-cmd is added to facilitate kernel tracing and diagnostics.
> packagegroup-qcom-utilities: enable hostapd and trace-cmd

- recipes-products/images/qcom-multimedia-proprietary-image.bb
Add an image, qcom-multimedia-proprietary-image, to showcase capabilities that are either missing or not fully supported in upstream, in areas such as camera, display, GPU, video and other multimedia components.
> Add an image to showcase proprietary features

- conf/distro/include/qcom-base.inc
- conf/distro/qcom-distro.conf
Now as the OE-Core has introduced the 'opencl' DISTRO_FEATURE, stop manually enabling Mesa's OpenCL PACKAGECONFIG entries and simply enable the 'opencl' DISTRO_FEATURE.
> qcom-distro: use opencl DISTRO_FEATURE

- conf/distro/include/qcom-base.inc
Enabling hardware watchdog is essential for collecting system dumps in case of hangs or crashes.
Set `WATCHDOG_RUNTIME_SEC` to 30 seconds for systemd recipe to ensure the `RuntimeWatchdogSec=` parameter in `/etc/systemd/system.conf` reflects this value, thereby activating the watchdog.
For implementation details of WATCHDOG_RUNTIME_SEC, refer to OE-Core revision: 1c61a1eb9c4faa9ab32b0440bbdd88c22c3cd945.
> Enable hardware watchdog support

- recipes-products/packagegroups/packagegroup-qcom-utilities.bb
The efivar utility has been added to the package group for debugging purposes.
This tool is essential for debugging boot-related issues, managing secure boot configurations, and inspecting system firmware behavior on UEFI-enabled platforms.
> packagegroup-qcom-utilities: Add efivar utility

- recipes-products/packagegroups/packagegroup-qcom-test-pkgs.bb
Integrating OpenCV libraries and its associated test binaries into the test image to ensure sanity of the OpenCV modules w.r.t functionality and Performance.
> packagegroup-qcom-test-pkg: add opencv-apps to test image

- recipes-products/images/qcom-multimedia-image.bb
Added the following recepies to multimedia-image to enable
GStreamer framework and plugins
gstreamer1.0
gstreamer1.0-plugins-base
gstreamer1.0-plugins-good
gstreamer1.0-plugins-bad
> qcom-multimedia-image: Enable GStreamer support
